// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface PyTorchRect ()
+ (PyTorchRect *)fromList:(NSArray *)list;
+ (nullable PyTorchRect *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface ResultObjectDetection ()
+ (ResultObjectDetection *)fromList:(NSArray *)list;
+ (nullable ResultObjectDetection *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation PyTorchRect
+ (instancetype)makeWithLeft:(NSNumber *)left
    top:(NSNumber *)top
    right:(NSNumber *)right
    bottom:(NSNumber *)bottom
    width:(NSNumber *)width
    height:(NSNumber *)height {
  PyTorchRect* pigeonResult = [[PyTorchRect alloc] init];
  pigeonResult.left = left;
  pigeonResult.top = top;
  pigeonResult.right = right;
  pigeonResult.bottom = bottom;
  pigeonResult.width = width;
  pigeonResult.height = height;
  return pigeonResult;
}
+ (PyTorchRect *)fromList:(NSArray *)list {
  PyTorchRect *pigeonResult = [[PyTorchRect alloc] init];
  pigeonResult.left = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.left != nil, @"");
  pigeonResult.top = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.top != nil, @"");
  pigeonResult.right = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.right != nil, @"");
  pigeonResult.bottom = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.bottom != nil, @"");
  pigeonResult.width = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.width != nil, @"");
  pigeonResult.height = GetNullableObjectAtIndex(list, 5);
  NSAssert(pigeonResult.height != nil, @"");
  return pigeonResult;
}
+ (nullable PyTorchRect *)nullableFromList:(NSArray *)list {
  return (list) ? [PyTorchRect fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.left ?: [NSNull null]),
    (self.top ?: [NSNull null]),
    (self.right ?: [NSNull null]),
    (self.bottom ?: [NSNull null]),
    (self.width ?: [NSNull null]),
    (self.height ?: [NSNull null]),
  ];
}
@end

@implementation ResultObjectDetection
+ (instancetype)makeWithClassIndex:(NSNumber *)classIndex
    className:(nullable NSString *)className
    score:(NSNumber *)score
    rect:(PyTorchRect *)rect {
  ResultObjectDetection* pigeonResult = [[ResultObjectDetection alloc] init];
  pigeonResult.classIndex = classIndex;
  pigeonResult.className = className;
  pigeonResult.score = score;
  pigeonResult.rect = rect;
  return pigeonResult;
}
+ (ResultObjectDetection *)fromList:(NSArray *)list {
  ResultObjectDetection *pigeonResult = [[ResultObjectDetection alloc] init];
  pigeonResult.classIndex = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.classIndex != nil, @"");
  pigeonResult.className = GetNullableObjectAtIndex(list, 1);
  pigeonResult.score = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.score != nil, @"");
  pigeonResult.rect = [PyTorchRect nullableFromList:(GetNullableObjectAtIndex(list, 3))];
  NSAssert(pigeonResult.rect != nil, @"");
  return pigeonResult;
}
+ (nullable ResultObjectDetection *)nullableFromList:(NSArray *)list {
  return (list) ? [ResultObjectDetection fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.classIndex ?: [NSNull null]),
    (self.className ?: [NSNull null]),
    (self.score ?: [NSNull null]),
    (self.rect ? [self.rect toList] : [NSNull null]),
  ];
}
@end

@interface ModelApiCodecReader : FlutterStandardReader
@end
@implementation ModelApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [PyTorchRect fromList:[self readValue]];
    case 129: 
      return [ResultObjectDetection fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface ModelApiCodecWriter : FlutterStandardWriter
@end
@implementation ModelApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PyTorchRect class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ResultObjectDetection class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface ModelApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation ModelApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[ModelApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[ModelApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *ModelApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    ModelApiCodecReaderWriter *readerWriter = [[ModelApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void ModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ModelApi> *api) {
  {
    NSObject<FlutterTaskQueue> *taskQueue = [binaryMessenger makeBackgroundTaskQueue];
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pytorch_lite.ModelApi.loadModel"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()
taskQueue:taskQueue];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadModelModelPath:numberOfClasses:imageWidth:imageHeight:objectDetectionModelType:completion:)], @"ModelApi api (%@) doesn't respond to @selector(loadModelModelPath:numberOfClasses:imageWidth:imageHeight:objectDetectionModelType:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_modelPath = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_numberOfClasses = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_imageWidth = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_imageHeight = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_objectDetectionModelType = GetNullableObjectAtIndex(args, 4);
        [api loadModelModelPath:arg_modelPath numberOfClasses:arg_numberOfClasses imageWidth:arg_imageWidth imageHeight:arg_imageHeight objectDetectionModelType:arg_objectDetectionModelType completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///predicts abstract number input
  {
    NSObject<FlutterTaskQueue> *taskQueue = [binaryMessenger makeBackgroundTaskQueue];
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pytorch_lite.ModelApi.getPredictionCustom"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()
taskQueue:taskQueue];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPredictionCustomIndex:input:shape:dtype:completion:)], @"ModelApi api (%@) doesn't respond to @selector(getPredictionCustomIndex:input:shape:dtype:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_index = GetNullableObjectAtIndex(args, 0);
        NSArray<NSNumber *> *arg_input = GetNullableObjectAtIndex(args, 1);
        NSArray<NSNumber *> *arg_shape = GetNullableObjectAtIndex(args, 2);
        NSString *arg_dtype = GetNullableObjectAtIndex(args, 3);
        [api getPredictionCustomIndex:arg_index input:arg_input shape:arg_shape dtype:arg_dtype completion:^(NSArray *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///predicts raw image but returns the raw net output
  {
    NSObject<FlutterTaskQueue> *taskQueue = [binaryMessenger makeBackgroundTaskQueue];
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pytorch_lite.ModelApi.getRawImagePredictionList"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()
taskQueue:taskQueue];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getRawImagePredictionListIndex:imageData:isTupleOutput:tupleIndex:completion:)], @"ModelApi api (%@) doesn't respond to @selector(getRawImagePredictionListIndex:imageData:isTupleOutput:tupleIndex:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_index = GetNullableObjectAtIndex(args, 0);
        FlutterStandardTypedData *arg_imageData = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_isTupleOutput = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_tupleIndex = GetNullableObjectAtIndex(args, 3);
        [api getRawImagePredictionListIndex:arg_index imageData:arg_imageData isTupleOutput:arg_isTupleOutput tupleIndex:arg_tupleIndex completion:^(NSArray<NSNumber *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///predicts raw image but returns the raw net output
  {
    NSObject<FlutterTaskQueue> *taskQueue = [binaryMessenger makeBackgroundTaskQueue];
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pytorch_lite.ModelApi.getRawImagePredictionListObjectDetection"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()
taskQueue:taskQueue];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getRawImagePredictionListObjectDetectionIndex:imageData:minimumScore:IOUThreshold:boxesLimit:isTupleOutput:tupleIndex:completion:)], @"ModelApi api (%@) doesn't respond to @selector(getRawImagePredictionListObjectDetectionIndex:imageData:minimumScore:IOUThreshold:boxesLimit:isTupleOutput:tupleIndex:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_index = GetNullableObjectAtIndex(args, 0);
        FlutterStandardTypedData *arg_imageData = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_minimumScore = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_IOUThreshold = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_boxesLimit = GetNullableObjectAtIndex(args, 4);
        NSNumber *arg_isTupleOutput = GetNullableObjectAtIndex(args, 5);
        NSNumber *arg_tupleIndex = GetNullableObjectAtIndex(args, 6);
        [api getRawImagePredictionListObjectDetectionIndex:arg_index imageData:arg_imageData minimumScore:arg_minimumScore IOUThreshold:arg_IOUThreshold boxesLimit:arg_boxesLimit isTupleOutput:arg_isTupleOutput tupleIndex:arg_tupleIndex completion:^(NSArray<ResultObjectDetection *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///predicts image but returns the raw net output
  {
    NSObject<FlutterTaskQueue> *taskQueue = [binaryMessenger makeBackgroundTaskQueue];
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pytorch_lite.ModelApi.getImagePredictionList"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()
taskQueue:taskQueue];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getImagePredictionListIndex:imageData:imageBytesList:imageWidthForBytesList:imageHeightForBytesList:mean:std:isTupleOutput:tupleIndex:completion:)], @"ModelApi api (%@) doesn't respond to @selector(getImagePredictionListIndex:imageData:imageBytesList:imageWidthForBytesList:imageHeightForBytesList:mean:std:isTupleOutput:tupleIndex:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_index = GetNullableObjectAtIndex(args, 0);
        FlutterStandardTypedData *arg_imageData = GetNullableObjectAtIndex(args, 1);
        NSArray<FlutterStandardTypedData *> *arg_imageBytesList = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_imageWidthForBytesList = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_imageHeightForBytesList = GetNullableObjectAtIndex(args, 4);
        NSArray<NSNumber *> *arg_mean = GetNullableObjectAtIndex(args, 5);
        NSArray<NSNumber *> *arg_std = GetNullableObjectAtIndex(args, 6);
        NSNumber *arg_isTupleOutput = GetNullableObjectAtIndex(args, 7);
        NSNumber *arg_tupleIndex = GetNullableObjectAtIndex(args, 8);
        [api getImagePredictionListIndex:arg_index imageData:arg_imageData imageBytesList:arg_imageBytesList imageWidthForBytesList:arg_imageWidthForBytesList imageHeightForBytesList:arg_imageHeightForBytesList mean:arg_mean std:arg_std isTupleOutput:arg_isTupleOutput tupleIndex:arg_tupleIndex completion:^(NSArray<NSNumber *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///predicts image but returns the output detections
  {
    NSObject<FlutterTaskQueue> *taskQueue = [binaryMessenger makeBackgroundTaskQueue];
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.pytorch_lite.ModelApi.getImagePredictionListObjectDetection"
        binaryMessenger:binaryMessenger
        codec:ModelApiGetCodec()
taskQueue:taskQueue];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getImagePredictionListObjectDetectionIndex:imageData:imageBytesList:imageWidthForBytesList:imageHeightForBytesList:minimumScore:IOUThreshold:boxesLimit:isTupleOutput:tupleIndex:completion:)], @"ModelApi api (%@) doesn't respond to @selector(getImagePredictionListObjectDetectionIndex:imageData:imageBytesList:imageWidthForBytesList:imageHeightForBytesList:minimumScore:IOUThreshold:boxesLimit:isTupleOutput:tupleIndex:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_index = GetNullableObjectAtIndex(args, 0);
        FlutterStandardTypedData *arg_imageData = GetNullableObjectAtIndex(args, 1);
        NSArray<FlutterStandardTypedData *> *arg_imageBytesList = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_imageWidthForBytesList = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_imageHeightForBytesList = GetNullableObjectAtIndex(args, 4);
        NSNumber *arg_minimumScore = GetNullableObjectAtIndex(args, 5);
        NSNumber *arg_IOUThreshold = GetNullableObjectAtIndex(args, 6);
        NSNumber *arg_boxesLimit = GetNullableObjectAtIndex(args, 7);
        NSNumber *arg_isTupleOutput = GetNullableObjectAtIndex(args, 8);
        NSNumber *arg_tupleIndex = GetNullableObjectAtIndex(args, 9);
        [api getImagePredictionListObjectDetectionIndex:arg_index imageData:arg_imageData imageBytesList:arg_imageBytesList imageWidthForBytesList:arg_imageWidthForBytesList imageHeightForBytesList:arg_imageHeightForBytesList minimumScore:arg_minimumScore IOUThreshold:arg_IOUThreshold boxesLimit:arg_boxesLimit isTupleOutput:arg_isTupleOutput tupleIndex:arg_tupleIndex completion:^(NSArray<ResultObjectDetection *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
