// Autogenerated from Pigeon (v22.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.abdelaziz_mahdy.pytorch_lite;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Pigeon {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class PyTorchRect {
    private @NonNull Double left;

    public @NonNull Double getLeft() {
      return left;
    }

    public void setLeft(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"left\" is null.");
      }
      this.left = setterArg;
    }

    private @NonNull Double top;

    public @NonNull Double getTop() {
      return top;
    }

    public void setTop(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"top\" is null.");
      }
      this.top = setterArg;
    }

    private @NonNull Double right;

    public @NonNull Double getRight() {
      return right;
    }

    public void setRight(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"right\" is null.");
      }
      this.right = setterArg;
    }

    private @NonNull Double bottom;

    public @NonNull Double getBottom() {
      return bottom;
    }

    public void setBottom(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"bottom\" is null.");
      }
      this.bottom = setterArg;
    }

    private @NonNull Double width;

    public @NonNull Double getWidth() {
      return width;
    }

    public void setWidth(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"width\" is null.");
      }
      this.width = setterArg;
    }

    private @NonNull Double height;

    public @NonNull Double getHeight() {
      return height;
    }

    public void setHeight(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"height\" is null.");
      }
      this.height = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PyTorchRect() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PyTorchRect that = (PyTorchRect) o;
      return left.equals(that.left) && top.equals(that.top) && right.equals(that.right) && bottom.equals(that.bottom) && width.equals(that.width) && height.equals(that.height);
    }

    @Override
    public int hashCode() {
      return Objects.hash(left, top, right, bottom, width, height);
    }

    public static final class Builder {

      private @Nullable Double left;

      @CanIgnoreReturnValue
      public @NonNull Builder setLeft(@NonNull Double setterArg) {
        this.left = setterArg;
        return this;
      }

      private @Nullable Double top;

      @CanIgnoreReturnValue
      public @NonNull Builder setTop(@NonNull Double setterArg) {
        this.top = setterArg;
        return this;
      }

      private @Nullable Double right;

      @CanIgnoreReturnValue
      public @NonNull Builder setRight(@NonNull Double setterArg) {
        this.right = setterArg;
        return this;
      }

      private @Nullable Double bottom;

      @CanIgnoreReturnValue
      public @NonNull Builder setBottom(@NonNull Double setterArg) {
        this.bottom = setterArg;
        return this;
      }

      private @Nullable Double width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@NonNull Double setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Double height;

      @CanIgnoreReturnValue
      public @NonNull Builder setHeight(@NonNull Double setterArg) {
        this.height = setterArg;
        return this;
      }

      public @NonNull PyTorchRect build() {
        PyTorchRect pigeonReturn = new PyTorchRect();
        pigeonReturn.setLeft(left);
        pigeonReturn.setTop(top);
        pigeonReturn.setRight(right);
        pigeonReturn.setBottom(bottom);
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(left);
      toListResult.add(top);
      toListResult.add(right);
      toListResult.add(bottom);
      toListResult.add(width);
      toListResult.add(height);
      return toListResult;
    }

    static @NonNull PyTorchRect fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PyTorchRect pigeonResult = new PyTorchRect();
      Object left = pigeonVar_list.get(0);
      pigeonResult.setLeft((Double) left);
      Object top = pigeonVar_list.get(1);
      pigeonResult.setTop((Double) top);
      Object right = pigeonVar_list.get(2);
      pigeonResult.setRight((Double) right);
      Object bottom = pigeonVar_list.get(3);
      pigeonResult.setBottom((Double) bottom);
      Object width = pigeonVar_list.get(4);
      pigeonResult.setWidth((Double) width);
      Object height = pigeonVar_list.get(5);
      pigeonResult.setHeight((Double) height);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ResultObjectDetection {
    private @NonNull Long classIndex;

    public @NonNull Long getClassIndex() {
      return classIndex;
    }

    public void setClassIndex(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"classIndex\" is null.");
      }
      this.classIndex = setterArg;
    }

    private @Nullable String className;

    public @Nullable String getClassName() {
      return className;
    }

    public void setClassName(@Nullable String setterArg) {
      this.className = setterArg;
    }

    private @NonNull Double score;

    public @NonNull Double getScore() {
      return score;
    }

    public void setScore(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"score\" is null.");
      }
      this.score = setterArg;
    }

    private @NonNull PyTorchRect rect;

    public @NonNull PyTorchRect getRect() {
      return rect;
    }

    public void setRect(@NonNull PyTorchRect setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"rect\" is null.");
      }
      this.rect = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ResultObjectDetection() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ResultObjectDetection that = (ResultObjectDetection) o;
      return classIndex.equals(that.classIndex) && Objects.equals(className, that.className) && score.equals(that.score) && rect.equals(that.rect);
    }

    @Override
    public int hashCode() {
      return Objects.hash(classIndex, className, score, rect);
    }

    public static final class Builder {

      private @Nullable Long classIndex;

      @CanIgnoreReturnValue
      public @NonNull Builder setClassIndex(@NonNull Long setterArg) {
        this.classIndex = setterArg;
        return this;
      }

      private @Nullable String className;

      @CanIgnoreReturnValue
      public @NonNull Builder setClassName(@Nullable String setterArg) {
        this.className = setterArg;
        return this;
      }

      private @Nullable Double score;

      @CanIgnoreReturnValue
      public @NonNull Builder setScore(@NonNull Double setterArg) {
        this.score = setterArg;
        return this;
      }

      private @Nullable PyTorchRect rect;

      @CanIgnoreReturnValue
      public @NonNull Builder setRect(@NonNull PyTorchRect setterArg) {
        this.rect = setterArg;
        return this;
      }

      public @NonNull ResultObjectDetection build() {
        ResultObjectDetection pigeonReturn = new ResultObjectDetection();
        pigeonReturn.setClassIndex(classIndex);
        pigeonReturn.setClassName(className);
        pigeonReturn.setScore(score);
        pigeonReturn.setRect(rect);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(classIndex);
      toListResult.add(className);
      toListResult.add(score);
      toListResult.add(rect);
      return toListResult;
    }

    static @NonNull ResultObjectDetection fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ResultObjectDetection pigeonResult = new ResultObjectDetection();
      Object classIndex = pigeonVar_list.get(0);
      pigeonResult.setClassIndex((Long) classIndex);
      Object className = pigeonVar_list.get(1);
      pigeonResult.setClassName((String) className);
      Object score = pigeonVar_list.get(2);
      pigeonResult.setScore((Double) score);
      Object rect = pigeonVar_list.get(3);
      pigeonResult.setRect((PyTorchRect) rect);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return PyTorchRect.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return ResultObjectDetection.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof PyTorchRect) {
        stream.write(129);
        writeValue(stream, ((PyTorchRect) value).toList());
      } else if (value instanceof ResultObjectDetection) {
        stream.write(130);
        writeValue(stream, ((ResultObjectDetection) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface ModelApi {

    void loadModel(@NonNull String modelPath, @Nullable Long numberOfClasses, @Nullable Long imageWidth, @Nullable Long imageHeight, @Nullable Long objectDetectionModelType, @NonNull Result<Long> result);
    /**predicts abstract number input */
    void getPredictionCustom(@NonNull Long index, @NonNull List<Double> input, @NonNull List<Long> shape, @NonNull String dtype, @NonNull NullableResult<List<Object>> result);
    /**predicts raw image but returns the raw net output */
    void getRawImagePredictionList(@NonNull Long index, @NonNull byte[] imageData, @NonNull Result<List<Double>> result);
    /**predicts raw image but returns the raw net output */
    void getRawImagePredictionListObjectDetection(@NonNull Long index, @NonNull byte[] imageData, @NonNull Double minimumScore, @NonNull Double IOUThreshold, @NonNull Long boxesLimit, @NonNull Result<List<ResultObjectDetection>> result);
    /**predicts image but returns the raw net output */
    void getImagePredictionList(@NonNull Long index, @Nullable byte[] imageData, @Nullable List<byte[]> imageBytesList, @Nullable Long imageWidthForBytesList, @Nullable Long imageHeightForBytesList, @NonNull List<Double> mean, @NonNull List<Double> std, @NonNull Result<List<Double>> result);
    /**predicts image but returns the output detections */
    void getImagePredictionListObjectDetection(@NonNull Long index, @Nullable byte[] imageData, @Nullable List<byte[]> imageBytesList, @Nullable Long imageWidthForBytesList, @Nullable Long imageHeightForBytesList, @NonNull Double minimumScore, @NonNull Double IOUThreshold, @NonNull Long boxesLimit, @NonNull Result<List<ResultObjectDetection>> result);

    /** The codec used by ModelApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `ModelApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable ModelApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable ModelApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pytorch_lite.ModelApi.loadModel" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String modelPathArg = (String) args.get(0);
                Long numberOfClassesArg = (Long) args.get(1);
                Long imageWidthArg = (Long) args.get(2);
                Long imageHeightArg = (Long) args.get(3);
                Long objectDetectionModelTypeArg = (Long) args.get(4);
                Result<Long> resultCallback =
                    new Result<Long>() {
                      public void success(Long result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.loadModel(modelPathArg, numberOfClassesArg, imageWidthArg, imageHeightArg, objectDetectionModelTypeArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pytorch_lite.ModelApi.getPredictionCustom" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Long indexArg = (Long) args.get(0);
                List<Double> inputArg = (List<Double>) args.get(1);
                List<Long> shapeArg = (List<Long>) args.get(2);
                String dtypeArg = (String) args.get(3);
                NullableResult<List<Object>> resultCallback =
                    new NullableResult<List<Object>>() {
                      public void success(List<Object> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getPredictionCustom(indexArg, inputArg, shapeArg, dtypeArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pytorch_lite.ModelApi.getRawImagePredictionList" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Long indexArg = (Long) args.get(0);
                byte[] imageDataArg = (byte[]) args.get(1);
                Result<List<Double>> resultCallback =
                    new Result<List<Double>>() {
                      public void success(List<Double> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getRawImagePredictionList(indexArg, imageDataArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pytorch_lite.ModelApi.getRawImagePredictionListObjectDetection" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Long indexArg = (Long) args.get(0);
                byte[] imageDataArg = (byte[]) args.get(1);
                Double minimumScoreArg = (Double) args.get(2);
                Double IOUThresholdArg = (Double) args.get(3);
                Long boxesLimitArg = (Long) args.get(4);
                Result<List<ResultObjectDetection>> resultCallback =
                    new Result<List<ResultObjectDetection>>() {
                      public void success(List<ResultObjectDetection> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getRawImagePredictionListObjectDetection(indexArg, imageDataArg, minimumScoreArg, IOUThresholdArg, boxesLimitArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pytorch_lite.ModelApi.getImagePredictionList" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Long indexArg = (Long) args.get(0);
                byte[] imageDataArg = (byte[]) args.get(1);
                List<byte[]> imageBytesListArg = (List<byte[]>) args.get(2);
                Long imageWidthForBytesListArg = (Long) args.get(3);
                Long imageHeightForBytesListArg = (Long) args.get(4);
                List<Double> meanArg = (List<Double>) args.get(5);
                List<Double> stdArg = (List<Double>) args.get(6);
                Result<List<Double>> resultCallback =
                    new Result<List<Double>>() {
                      public void success(List<Double> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getImagePredictionList(indexArg, imageDataArg, imageBytesListArg, imageWidthForBytesListArg, imageHeightForBytesListArg, meanArg, stdArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BinaryMessenger.TaskQueue taskQueue = binaryMessenger.makeBackgroundTaskQueue();
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pytorch_lite.ModelApi.getImagePredictionListObjectDetection" + messageChannelSuffix, getCodec(), taskQueue);
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                Long indexArg = (Long) args.get(0);
                byte[] imageDataArg = (byte[]) args.get(1);
                List<byte[]> imageBytesListArg = (List<byte[]>) args.get(2);
                Long imageWidthForBytesListArg = (Long) args.get(3);
                Long imageHeightForBytesListArg = (Long) args.get(4);
                Double minimumScoreArg = (Double) args.get(5);
                Double IOUThresholdArg = (Double) args.get(6);
                Long boxesLimitArg = (Long) args.get(7);
                Result<List<ResultObjectDetection>> resultCallback =
                    new Result<List<ResultObjectDetection>>() {
                      public void success(List<ResultObjectDetection> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.getImagePredictionListObjectDetection(indexArg, imageDataArg, imageBytesListArg, imageWidthForBytesListArg, imageHeightForBytesListArg, minimumScoreArg, IOUThresholdArg, boxesLimitArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
