// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart' as pkg_ffi;

/// Bindings to `headers/example.h`.
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int load_ml_model(
    ffi.Pointer<pkg_ffi.Utf8> model_path,
  ) {
    return _load_ml_model(
      model_path,
    );
  }

  late final _load_ml_modelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<pkg_ffi.Utf8>)>>(
          'load_ml_model');
  late final _load_ml_model =
      _load_ml_modelPtr.asFunction<int Function(ffi.Pointer<pkg_ffi.Utf8>)>();

  ffi.Pointer<pkg_ffi.Utf8> getPrintingBufferAndClear() {
    return _getPrintingBufferAndClear();
  }

  late final _getPrintingBufferAndClearPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<pkg_ffi.Utf8> Function()>>(
          'getPrintingBufferAndClear');
  late final _getPrintingBufferAndClear = _getPrintingBufferAndClearPtr
      .asFunction<ffi.Pointer<pkg_ffi.Utf8> Function()>();

  ffi.Pointer<ffi.Pointer<ffi.Float>> modelInference(
    ffi.Pointer<ffi.Float> input_data_ptr,
  ) {
    return _modelInference(
      input_data_ptr,
    );
  }

  late final _modelInferencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Float>> Function(
              ffi.Pointer<ffi.Float>)>>('modelInference');
  late final _modelInference = _modelInferencePtr.asFunction<
      ffi.Pointer<ffi.Pointer<ffi.Float>> Function(ffi.Pointer<ffi.Float>)>();

  ffi.Pointer<ffi.Float> image_model_inference(
    int index,
    ffi.Pointer<ffi.UnsignedChar> data,
    int width,
    int height,
  ) {
    return _image_model_inference(
      index,
      data,
      width,
      height,
    );
  }

  late final _image_model_inferencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Float> Function(
              ffi.Int,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Int,
              ffi.Int)>>('image_model_inference');
  late final _image_model_inference = _image_model_inferencePtr.asFunction<
      ffi.Pointer<ffi.Float> Function(
          int, ffi.Pointer<ffi.UnsignedChar>, int, int)>();
}
